env:
  browser: true
  es2020: true
  node: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  object-curly-spacing: 0
  space-before-function-paren: 0
  semi: ['error', 'always']
  quotes: ['error', 'double']
  